import os
import requests
import json
from datetime import datetime

OLLAMA_URL = os.getenv("OLLAMA_HOST", "http://localhost:11434/api/generate")
MODEL_NAME = os.getenv("OLLAMA_MODEL", "llama3.2:3b")

def generate_analytics_notebook():
    """Asks Llama to generate a complete Pandas/Plotly data analysis notebook, safely parsing markdown blocks."""
    
    prompt = (
        "You are an expert Data Science Analytics Architect. "
        "Create a valid Jupyter Notebook JSON object (.ipynb format version 4) containing markdown and code cells "
        "that connect to a PostgreSQL database using pandas and psycopg2, query real estate permit tables ('leads', 'prospect_features'), "
        "and build a Plotly visualization histogram or scatter plot. "
        "CRITICAL REQUIREMENT: Output ONLY valid raw JSON. Do not write any conversational text. "
        "If you use markdown code ticks, ensure they are stripped so the output is parseable by json.loads()."
    )

    try:
        payload = {"model": MODEL_NAME, "prompt": prompt, "stream": False}
        print(f"[*] Requesting analytics notebook from Llama ({MODEL_NAME})...")
        response = requests.post(OLLAMA_URL, json=payload, timeout=60)
        
        if response.status_code == 200:
            raw_text = response.json().get("response", "").strip()
            
            # Robustly extract JSON if enclosed in markdown code blocks
            if "```json" in raw_text:
                raw_text = raw_text.split("```json")[1].split("```")[0].strip()
            elif "```" in raw_text:
                raw_text = raw_text.split("```")[1].split("```")[0].strip()
                
            notebook_data = json.loads(raw_text)
            
            filename = f"generated_analytics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.ipynb"
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(notebook_data, f, indent=2)
            print(f"[+] Successfully generated dynamic notebook: {filename}")
            return filename
            
    except Exception as e:
        print(f"[-] LLM JSON generation error: {e}. Falling back to rich architected template.")

    # Comprehensive fully-populated fallback notebook template if parsing fails
    rich_fallback_nb = {
      "cells": [
       {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
         "# 🏡 East Bay Real Estate: Automated Permit & Spatial Analytics\n",
         "This notebook was auto-generated by your local **Analytics Architect Agent** to analyze lead momentum and permit velocity."
        ]
       },
       {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
         "import os\n",
         "import pandas as pd\n",
         "import psycopg2\n",
         "import plotly.express as px\n\n",
         "# Establish connection to production database via environment variables\n",
         "conn = psycopg2.connect(os.environ.get('DATABASE_URL'))\n",
         "query = '''\n",
         "    SELECT l.address, l.city, l.status, \n",
         "           COALESCE(f.building_permit_count_24m, 0) as building_permit_count_24m,\n",
         "           COALESCE(f.project_count, 0) as project_count\n",
         "    FROM leads l\n",
         "    LEFT JOIN prospect_features f ON l.id = f.lead_id\n",
         "    ORDER BY building_permit_count_24m DESC\n",
         "    LIMIT 200\n",
         "'''\n",
         "df = pd.read_sql(query, conn)\n",
         "conn.close()\n\n",
         "print(f'Loaded {len(df)} records for analysis.')\n",
         "df.head()"
        ]
       },
       {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
         "# Visualize Permit Momentum Distribution\n",
         "fig = px.histogram(\n",
         "    df, \n",
         "    x='building_permit_count_24m', \n",
         "    nbins=15, \n",
         "    title='Distribution of 24-Month Building Permits across Target Leads',\n",
         "    labels={'building_permit_count_24m': 'Permit Count'},\n",
         "    color_discrete_sequence=['#2b5c8f']\n",
         ")\n",
         "fig.show()"
        ]
       }
      ],
      "metadata": {
       "language_info": {
        "name": "python"
       }
      },
      "nbformat": 4,
      "nbformat_minor": 2
    }
    
    filename = f"generated_analytics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.ipynb"
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(rich_fallback_nb, f, indent=2)
    return filename

if __name__ == "__main__":
    nb = generate_analytics_notebook()
    print(f"Generated notebook: {nb}")