[deploy]
restartPolicyType = "always"


[services.scheduler]
name = "scheduler"
startCommand = "python3 -u -m automation_engine.scheduler"


[services.agent]
name = "agent"
startCommand = "python3 -u -m automation_engine.agent"