from datetime import datetime
from pathlib import Path


def create_proposal(
    category,
    name,
    description,
    files=None
):

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    folder = (
        Path("proposals")
        / category
    )

    folder.mkdir(
        parents=True,
        exist_ok=True
    )


    filename = (
        folder
        /
        f"{name}_{timestamp}.md"
    )


    content = f"""
# Feature Proposal

Created:
{datetime.now()}


## Name

{name}


## Description

{description}


## Potential Files

{files or "None identified"}


## Status

PENDING HUMAN REVIEW

"""


    filename.write_text(
        content
    )


    return str(filename)


if __name__ == "__main__":

    result = create_proposal(
        "features",
        "example_agent_capability",
        "Example proposal generated by the proposal engine.",
        [
            "automation_engine/agent.py"
        ]
    )

    print(result)
